### PR TITLE
fix: tab order and other UI tweaks

### LINKED ISSUE #77: Verify tab order of plugins is correct

### PR DESCRIPTION
**Pull request by dylandepass**
- [x] Fix tab order for plugins and menus
- [x] Fix focus styling of action buttons and pickers
- [x] UI Tweaks to menus
- [x] Tests

fixes #77

### CODE REVIEW

**Review by rofe — CHANGES_REQUESTED** [review]
Found a styling isssue in the picker:
image

Nit: pressing the `alt` key while a picker is open also makes the focus visible. This is a bit unexpected (at least for me), and it makes it cumbersome to take screenshots of an open picker without focused child item...

**Comment by dylandepass** [comment]
> Found a styling isssue in the picker: image
> 
> Nit: pressing the `alt` key while a picker is open also makes the focus visible. This is a bit unexpected (at least for me), and it makes it cumbersome to take screenshots of an open picker without focused child item...

Fixed the styling issue. 

Re the `alt` key, this is [default functionality](https://opensource.adobe.com/spectrum-web-components/components/picker/#sizes) coming from swc. So I'm hesitant to change it, I have to imagine they are doing this for accessibility reasons I'm not aware of. wdyt?

**Comment by rofe** [comment]
Another (minor but unexpected) issue i stumbled upon:
1. Tab to the env switcher
2. Open it via `space` or `return`
3. If not already focused, place the focus on "Open in ..."
4. Close the env switcher via `esc`
5. Hit the right arrow (i accidentally used this instead of tab to shft focus to the next button)
6. "Open in ..." action gets executed

My expectation would be that nothing happens at step 5. Also, pressing the left arrow key has no effect in the open menu.

**Review by rofe — APPROVED** [review]

**Pull request merged**
