### PR TITLE
feat: support development environment in switcher

### PR DESCRIPTION
**Pull request by dylandepass**
Added missing dev environment in envSwitcher when running on localhost.

### CODE REVIEW

**Comment by dylandepass** [comment]
Not sure if `Development` should show the Last mod date for preview?

Screenshot 2024-03-07 at 2 35 29 PM

**Comment by rofe** [comment]
> Not sure if `Development` should show the Last mod date for preview?

Hmm, since development is not actually a content environment per se, it depends on which env is being proxied by the simulator. This info could be derived from the `hlx:proxyUrl` meta tag.

**Comment by dylandepass** [comment]
Development will now show the `preview` last mod date.

**Review by rofe — APPROVED** [review]

**Pull request merged**
